## Copyright (C) 2011, 2012 Robert Lipshitz and Sucharit Sarkar.
## Pure Python port (C) 2026.
## Licensed under GPLv3.

"""
computehom.py -- Compute Khovanov homology ranks directly (slow path)
and write allhom.sage.

Usage:  python computehom.py
Input:  alldata.sage  (generated by convert.py)
Output: allhom.sage
"""

import sys
from main import (CycList, ResolvedKnot, KnotKh,
                  populate_vertices, populate_edges, chain_groups, chain_maps,
                  complexes)

outp = 'allhom.sage'

# Load alldata.sage into the current namespace
_ns = {'CycList': CycList, 'ResolvedKnot': ResolvedKnot}
with open('alldata.sage') as _f:
    exec(_f.read(), _ns)

all_knots = _ns['all']

with open(outp, 'w') as writing:
    for s in all_knots:
        resolved_knot = _ns[s + '_resolved_knot']
        cross         = _ns[s + '_cross']

        Central_Knot = KnotKh(resolved_knot, cross, print_progress=False)

        hom_rank    = Central_Knot.hom_rank()
        writing.write('\n' + s + '_hom=' + repr(hom_rank) + '\n')
        writing.flush()
        print(s, 'done')
