## Copyright (C) 2011, 2012 Robert Lipshitz and Sucharit Sarkar.
## Pure Python port (C) 2026.
## Licensed under GPLv3.

"""
texify.py -- Convert result.sage into a LaTeX table (out.tex).

Usage:  python texify.py
Input:  result.sage  (generated by batch.py / batch.sage)
Output: out.tex
"""

import numpy as np
from gf2 import GF2Matrix

# ---------------------------------------------------------------------------
# Load result.sage
# ---------------------------------------------------------------------------

_ns = {}
with open('result.sage') as _f:
    exec(_f.read(), _ns)

all_knots = _ns['all']

# ---------------------------------------------------------------------------
# Generate LaTeX output
# ---------------------------------------------------------------------------

with open('out.tex', 'w') as writing:
    for K in all_knots:
        is_trivial = True

        hom = _ns.get(K + '_hom', {})
        sq1 = _ns.get(K + '_sq1', {})
        sq2 = _ns.get(K + '_sq2', {})

        # hom may be stored as a dict or as a list of ((t,q), rank) pairs
        if isinstance(hom, list):
            hom = dict(hom)

        st = dict()

        for (t, q) in sq2.keys():
            # Build matrices from stored row lists
            m_tq     = hom.get((t, q), 0)
            m_tplus2 = hom.get((t+2, q), 0)
            m_tplus1 = hom.get((t+1, q), 0)

            rows_sq2 = sq2[(t, q)]
            if rows_sq2 and m_tq > 0 and m_tplus2 > 0:
                whole = GF2Matrix.from_rows(rows_sq2)
            else:
                whole = GF2Matrix(m_tq, m_tplus2)

            if (t+1, q) in hom:
                rows_sq1_t    = sq1.get((t, q), [])
                rows_sq1_tp1  = sq1.get((t+1, q), [])
                if rows_sq1_t and m_tq > 0 and m_tplus1 > 0:
                    tail = GF2Matrix.from_rows(rows_sq1_t)
                else:
                    tail = GF2Matrix(m_tq, m_tplus1)
                if rows_sq1_tp1 and m_tplus1 > 0 and m_tplus2 > 0:
                    head = GF2Matrix.from_rows(rows_sq1_tp1)
                else:
                    head = GF2Matrix(m_tplus1, m_tplus2)
            else:
                tail = GF2Matrix(m_tq, 0)
                head = GF2Matrix(0, m_tplus2)

            a = whole.rank()
            if a > 0:
                is_trivial = False

                st[(t, q)] = [0, 0, 0, 0]
                st[(t, q)][0] = a

                ker_basis  = tail.kernel().basis()        # {v : v @ tail = 0}
                if ker_basis:
                    ker_mat    = GF2Matrix.from_rows(ker_basis)
                    restricted = GF2Matrix.from_rows(
                        [(np.asarray(v, dtype=np.int32) @
                          whole._m.astype(np.int32) % 2).astype(np.uint8)
                         for v in ker_basis]
                    )
                else:
                    restricted = GF2Matrix(0, m_tplus2)

                st[(t, q)][1] = restricted.rank()

                im = head.row_space()

                if im.rank() > 0:
                    st[(t, q)][2] = whole.row_space().intersection(im).rank()
                    if st[(t, q)][1] > 0:
                        st[(t, q)][3] = restricted.row_space().intersection(im).rank()

                [r1, r2, r3, r4] = st[(t, q)]
                st[(t, q)] = [r2-r4, r1-r2-r3+r4, r4, r3-r4]

        if not is_trivial:
            K_first = K[0]
            K_tex = K
            if K_first == 'R':
                K_tex = K_tex.lstrip('R').replace('_', '_{') + '}'
            if K_first == 'K':
                K_tex = K_tex.replace('K', '\\text{K}')
            if K_first == 'L':
                K_tex = K_tex.replace('L', '\\text{L}')
            writing.write('$' + K_tex + '$ & ')

            first_item = True
            for x in st.keys():
                if not first_item:
                    writing.write(', ')
                else:
                    first_item = False
                writing.write('$' + repr(x) + '\\mapsto ' + repr(tuple(st[x])) + '$')
            writing.write('\\\\\n')
            writing.flush()
